# Generated by Django 5.2.1 on 2025-07-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionl_bids_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionl',
            name='bid_start',
            field=models.DecimalField(decimal_places=3, max_digits=20),
        ),
        migrations.AlterField(
            model_name='bids',
            name='bid',
            field=models.DecimalField(decimal_places=3, max_digits=20),
        ),
    ]
