# Generated by Django 5.2.1 on 2025-07-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_auctionl_bid_start_alter_bids_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionl',
            name='title',
            field=models.CharField(default='default title', max_length=64),
            preserve_default=False,
        ),
    ]
