# Generated by Django 5.2.1 on 2025-07-10 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auctionl_creator_auctionl_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auctionl',
            old_name='bid_start',
            new_name='price',
        ),
    ]
