# Generated by Django 5.2.1 on 2025-07-16 16:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_rename_bid_start_auctionl_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionl',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
