# Generated by Django 5.2.1 on 2025-07-22 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_bids_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionl',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=10),
        ),
    ]
