# Generated by Django 5.2.1 on 2025-07-26 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_alter_auctionl_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='item_won',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.auctionl'),
        ),
    ]
