# Generated by Django 5.2.1 on 2025-07-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_user_item_won'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='item_won',
        ),
        migrations.AddField(
            model_name='user',
            name='item_won',
            field=models.ManyToManyField(blank=True, null=True, to='auctions.auctionl'),
        ),
    ]
