# Generated by Django 5.2.1 on 2025-07-26 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_remove_user_item_won_user_item_won'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='item_won',
        ),
        migrations.AddField(
            model_name='auctionl',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner', to=settings.AUTH_USER_MODEL),
        ),
    ]
