# Generated by Django 5.2.1 on 2025-07-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_remove_user_item_won_auctionl_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionl',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
